Repository Spectrum-CETB/Hello-World, pull requests merged in 2020-10, with the labels that each got.

#11 Hello world programme in java
  Java/Readme.md
  Java/helloworld.java
Labels: Review Required

#2 Added code for Hello world in python
  C/hello.c
  Java/Hello.java
  Python/hello.py
Labels: Review Required

#5 Added code for hello world
  C/hello.c
  Java/Hello.java
  Python/hello.py
Labels: Review Required

#6 Create helloworld.rs
  Rust/helloworld.rs
Labels: Review Required

#9 A hello world programme in C language
  C/helloworld.c
  C/readme.md
Labels: Review Required

#20 Added hello world program in Julia language
  Julia/README.md
  Julia/hello_world.jl
  Python/hello_world.py
Labels: Review Required

#25 Hello World in perl language
  Java/Readme.md
  Java/helloworld.java
  perl/helloworld.pl
  perl/readme.md
Labels: hacktoberfest-accepted

#28 Hello World Program in Python
  Hello World-Prajojita.java
  Python/hello world-Prajojita.py
Labels: Review Required

#18 Hello World in GO
  GoLang/README.md
  GoLang/hello_world.go
Labels: Approved, Ready to merge, hacktoberfest-accepted

#31 Hello world in Scala
  Scala/hello.scala
Labels: Review Required

#32 Hello World in Python
  CPP/helloworld-kshitij.cpp
  Python/helloworld-kshitij.py
Labels: Review Required

#39 Create helloworld.hs
  Haskell/helloworld.hs
Labels: Approved, Ready to merge, hacktoberfest-accepted
